# Generated by Django 4.2.11 on 2026-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('money_market', 'Money Market Account'), ('business', 'Business Account')], default='checking', max_length=50),
        ),
    ]
